### ISSUE TITLE
Bootcamp Feedback TODO

### ISSUE THREAD

**Issue by danilolab** [NiEl0503/BurgerBots#77]
Deixo como sugestão os seguintes tópicos:
- [ ] Aprofundar os estudos no Angular, quanto à modularização e componentização
- [ ] Escrever os testes unitários
- [ ] Estudar NestJS: https://nestjs.com/
- [ ] Criar projetos pessoais, para crianças e/ou familiares e publicar no git para demonstrar seus conhecimentos
- [ ] Refazer alguns exercícios da GYM focados em design e backend
- [ ] Recomendação de sites: https://www.hackerrank.com/, https://leetcode.com/ e https://www.codewars.com/
